name: Claude Review After CI

on:
  workflow_run:
    workflows: ["CI - Basic Checks"]
    types: [completed]
    branches-ignore: [main]

jobs:
  claude-review:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: read
      id-token: write
    
    steps:
      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`,
              state: 'open'
            });
            
            if (pullRequests.length === 0) {
              core.setFailed('No open pull request found for this branch');
              return;
            }
            
            const pr = pullRequests[0];
            core.setOutput('number', pr.number);
            core.setOutput('sha', pr.head.sha);
            return pr.number;

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.sha }}
          fetch-depth: 0

      - name: Check if review already exists
        id: check-review
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.pr.outputs.number }}
            });
            
            const claudeReview = reviews.find(review => 
              review.user.login === 'github-actions[bot]' && 
              review.body && 
              review.body.includes('Claude Code レビュー')
            );
            
            core.setOutput('exists', claudeReview ? 'true' : 'false');

      - name: Run Claude Review
        if: steps.check-review.outputs.exists == 'false'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.pr.outputs.number }}
          custom_instructions: |
            日本語で応答してください。
            このPRのレビューをお願いします。すべてのCIチェックが通過した後のレビューです。
          direct_prompt: |
            # Claude Code レビュー

            すべてのCIチェックが正常に完了したため、コードレビューを実施します。

            ## 重点確認項目
            - コード品質とベストプラクティス
            - 潜在的なバグや問題
            - パフォーマンスの考慮事項
            - セキュリティへの影響
            - テストカバレッジ
            - ドキュメントの更新が必要かどうか

            改善提案がある場合は、具体的で建設的なフィードバックを提供してください。
            インラインコメントを使用して、特定の問題箇所を明確に指摘してください。

            **注意**: このレビューはCIが全て成功した後に実行されています。